// Code generated by MockGen. DO NOT EDIT.
// Source: prompter.go

// Package mock_prompter is a generated GoMock package.
package mock_prompter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// ReadStringFromPrompt mocks base method.
func (m *MockPrompter) ReadStringFromPrompt(label, defVal string, password bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStringFromPrompt", label, defVal, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStringFromPrompt indicates an expected call of ReadStringFromPrompt.
func (mr *MockPrompterMockRecorder) ReadStringFromPrompt(label, defVal, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStringFromPrompt", reflect.TypeOf((*MockPrompter)(nil).ReadStringFromPrompt), label, defVal, password)
}
